---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "notifications-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "notifications"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.notifications.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.notifications.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.notifications.cache_password }}@cache-service:6379"
  ConnectionStrings__messaging: "amqp://guest:{{ .Values.secrets.notifications.messaging_password }}@messaging-service:5672"
  MESSAGING_PASSWORD: "{{ .Values.secrets.notifications.messaging_password }}"
  MESSAGING_URI: "amqp://guest:{{ .Values.secrets.notifications.messaging_password }}@messaging-service:5672"
type: "Opaque"
