parameters:
  screenings:
    port_http: 8080
    screenings_image: "screenings:latest"
  bookings:
    port_http: 8080
    bookings_image: "bookings:latest"
  payments:
    port_http: 8080
    payments_image: "payments:latest"
  notifications:
    port_http: 8080
    notifications_image: "notifications:latest"
  gateway:
    port_http: 8080
    gateway_image: "gateway:latest"
secrets:
  postgres:
    postgres_password: ""
  cache:
    cache_password: ""
  messaging:
    messaging_password: ""
  screenings:
    ConnectionStrings__screenings_db: ""
    postgres_password: ""
    SCREENINGS_DB_URI: ""
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
    ConnectionStrings__messaging: ""
    messaging_password: ""
    MESSAGING_URI: ""
  bookings:
    ConnectionStrings__bookings_db: ""
    postgres_password: ""
    BOOKINGS_DB_URI: ""
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
    ConnectionStrings__messaging: ""
    messaging_password: ""
    MESSAGING_URI: ""
  payments:
    ConnectionStrings__payments_db: ""
    postgres_password: ""
    PAYMENTS_DB_URI: ""
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
    ConnectionStrings__messaging: ""
    messaging_password: ""
    MESSAGING_URI: ""
  notifications:
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
    ConnectionStrings__messaging: ""
    messaging_password: ""
    MESSAGING_URI: ""
  gateway:
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
config:
  postgres:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  messaging:
    RABBITMQ_DEFAULT_USER: "guest"
  screenings:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    SCREENINGS_DB_HOST: "postgres-service"
    SCREENINGS_DB_PORT: "5432"
    SCREENINGS_DB_USERNAME: "postgres"
    SCREENINGS_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/screenings"
    SCREENINGS_DB_DATABASENAME: "screenings"
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    MESSAGING_HOST: "messaging-service"
    MESSAGING_PORT: "5672"
    MESSAGING_USERNAME: "guest"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "screenings"
  bookings:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    BOOKINGS_DB_HOST: "postgres-service"
    BOOKINGS_DB_PORT: "5432"
    BOOKINGS_DB_USERNAME: "postgres"
    BOOKINGS_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/bookings"
    BOOKINGS_DB_DATABASENAME: "bookings"
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    MESSAGING_HOST: "messaging-service"
    MESSAGING_PORT: "5672"
    MESSAGING_USERNAME: "guest"
    SCREENINGS_HTTP: ""
    services__screenings__http__0: ""
    SCREENINGS_HTTPS: ""
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "bookings"
  payments:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    PAYMENTS_DB_HOST: "postgres-service"
    PAYMENTS_DB_PORT: "5432"
    PAYMENTS_DB_USERNAME: "postgres"
    PAYMENTS_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/payments"
    PAYMENTS_DB_DATABASENAME: "payments"
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    MESSAGING_HOST: "messaging-service"
    MESSAGING_PORT: "5672"
    MESSAGING_USERNAME: "guest"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "payments"
  notifications:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    MESSAGING_HOST: "messaging-service"
    MESSAGING_PORT: "5672"
    MESSAGING_USERNAME: "guest"
    Mail__Host: "mail-service"
    Mail__Port: "1025"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "notifications"
  gateway:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    SCREENINGS_HTTP: ""
    services__screenings__http__0: ""
    SCREENINGS_HTTPS: ""
    BOOKINGS_HTTP: ""
    services__bookings__http__0: ""
    BOOKINGS_HTTPS: ""
    PAYMENTS_HTTP: ""
    services__payments__http__0: ""
    PAYMENTS_HTTPS: ""
    NOTIFICATIONS_HTTP: ""
    services__notifications__http__0: ""
    NOTIFICATIONS_HTTPS: ""
    Demo__DashboardUrl: ""
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "gateway"
