---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mail-service"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "mail"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "mail"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "web"
      protocol: "TCP"
      port: 8025
      targetPort: 8025
    - name: "smtp"
      protocol: "TCP"
      port: 1025
      targetPort: 1025
