---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gateway-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.gateway.port_http | int | toString }}"
  CACHE_HOST: "{{ .Values.config.gateway.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.gateway.CACHE_PORT }}"
  SCREENINGS_HTTP: "http://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  services__screenings__http__0: "http://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  SCREENINGS_HTTPS: "https://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  BOOKINGS_HTTP: "http://bookings-service:{{ .Values.parameters.bookings.port_http }}"
  services__bookings__http__0: "http://bookings-service:{{ .Values.parameters.bookings.port_http }}"
  BOOKINGS_HTTPS: "https://bookings-service:{{ .Values.parameters.bookings.port_http }}"
  PAYMENTS_HTTP: "http://payments-service:{{ .Values.parameters.payments.port_http }}"
  services__payments__http__0: "http://payments-service:{{ .Values.parameters.payments.port_http }}"
  PAYMENTS_HTTPS: "https://payments-service:{{ .Values.parameters.payments.port_http }}"
  NOTIFICATIONS_HTTP: "http://notifications-service:{{ .Values.parameters.notifications.port_http }}"
  services__notifications__http__0: "http://notifications-service:{{ .Values.parameters.notifications.port_http }}"
  NOTIFICATIONS_HTTPS: "https://notifications-service:{{ .Values.parameters.notifications.port_http }}"
  Demo__DashboardUrl: "{{ .Values.config.gateway.Demo__DashboardUrl }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.gateway.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.gateway.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.gateway.OTEL_SERVICE_NAME }}"
