---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "gateway-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.gateway.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.gateway.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.gateway.cache_password }}@cache-service:6379"
type: "Opaque"
