---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "screenings-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "screenings"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__screenings-db: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.screenings.postgres_password }};Database=screenings"
  SCREENINGS_DB_PASSWORD: "{{ .Values.secrets.screenings.postgres_password }}"
  SCREENINGS_DB_URI: "postgresql://postgres:{{ .Values.secrets.screenings.postgres_password }}@postgres-service:5432/screenings"
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.screenings.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.screenings.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.screenings.cache_password }}@cache-service:6379"
  ConnectionStrings__messaging: "amqp://guest:{{ .Values.secrets.screenings.messaging_password }}@messaging-service:5672"
  MESSAGING_PASSWORD: "{{ .Values.secrets.screenings.messaging_password }}"
  MESSAGING_URI: "amqp://guest:{{ .Values.secrets.screenings.messaging_password }}@messaging-service:5672"
type: "Opaque"
