apiVersion: v1
kind: Secret
metadata:
    name: demo-kino-secrets
    namespace: demo-kino
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Fa1dDj+DYdFopDFxUDT6AUaztE9+9DfFo/MKzbF/HAVhaT5OY4YU2C8sIZRVT4S4bnRLwad3t6AWxn4qPhrAbTi+zuVhVQviu1JlsM8zwTP9APZY0MOAQX6xyz+7g7Cw/RxSzm0jDwIUiugwGEtz4mXyFUf07sR8Q3FPH4tof8K2xVNyKIlz0hnp5I2AX0C5WROJEjIpfd8CkrN7ykDC2H3EUdi4HBkH83Vs8oLDIGqtZIA6JECeYTb/de7OA9CMLp+jK4VQsejmkLVqr1w/4QEUkVKqfLHId1YClG3cOs11C2cMTI+1m1u6kENiQI7w24oefBNg//Upl4t6kH9P3l1D0lgGgM9LD25zmOm9jSWWnr/LpiX3MbJLvUym/LKvvIg5FEU/BwVKQM2nqOlGa38lVCxXn5LzOWGCvXjXhu/0AzForX3CtJKdJtb6hrJQr/id6Dn6uwaL6b0rGERjnzNV2oUEipbkGMtdN9rJbCOEmcdbkwz8pHh4zWgamvPCypBSB/aVV9dHdSQhnKGkB6f6CDHdDGlN57ufYJhGeQxk6adtqiHMI4ofHz8WXsqLMpXXDh4imtz4YSv1dG6Xne8GbITDg/HLCpc/CNmpSW8H5h4uNaKY4toRGqhSrtUlLfpyvk9hubPAPq2nTgJW1J60EcdL/5RV1e4sc7Vu0frRGVbNcT+yuLzNspHL/SYemBDsfUCsrKxSIKkp5JOQV+xXhzCaJq/tuBsw6Kyef26p7OAm3E+Djs4dOBK5YeRLFnvE1wKG7Y0v9xR7BZi2NFV5aiaAAZcfqs8l6/jC1UNIaoWCSqxo+tDCxWe12o5LMCR8uFoVBBwwxs8eLZr5e8Q1hMUjagEneJOjYJWFQP7xy0LX27jCCkfrbv6VuzhgqFs8faOkNxEkQJDUDesT+j6MSUogtrrT39xweH/coadyjPuuaiAK/JHIjcSrJBgJmGIPLv/q9CSHt3QH6fGOVrsSNcsudtopltFD5eGXtbs9vNqSahHc6snesObNnAUMXRiLz0jl35eiRXe0s1kki9ndmOwYifRt9JEzMXhAyBlAIEBcxg6TNixIPTrQELqBG4aPlWN0aWGdsgC6ZJquV8zUDN/inzXX/42ggSo=,iv:bTB4By3Qj9JpUundm+FA3eHTNL+32x8rarxmFQnpXf4=,tag:aORKbIiryAM9baHUw3HEIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YmVJQ1JQYXNyYVNEUFZW
            S1hxVElmMVhGbEZpREdweHgyeDN6TkZZd25ZCnNXRXpJaGYrbjJ3eWtyUzJNY3ov
            czc3VDdydXRzVGgxOUxqT0ZEM05qLzAKLS0tIHVKZkpycVVyWmR1bUhGWkxoMTIx
            N3UrRnNrOXQ0NXNOZzVwcHNiVGh1eGMK/WiFMuHah/Mh6gDLyjBSkrF47q1ABZEa
            OQv342r8/iTEXM8cyNytKRA69p4qWaqnkwZU63BSrJU2lyLFhH2Jvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16nr43tw34aqh7jknd3syqyamwn862dd063ezuac39paz7m4nverq79gxpe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T15:53:08Z"
    mac: ENC[AES256_GCM,data:6WwXfcxE7YPiOvkZPdxi4maQXNsNEHgauoPFtScjHSffDQKmlzAGfAA5qO7GUu0/OkL5K4DprrxuiSvkrnoOnOh7cb+BBH+Nv5nPz9Nt4DO5X542u4/Bh/X2wmhRi8MaHStEyGfsoJt3Sp+CGXXlV6GYgi8cLB/a0IecRCUaUKY=,iv:wMXnb6cxHcnJHSe2ja3N2dA8sAxyN2SzNIeshIIfjRU=,tag:p6LNwWBXHAC7KsYEjYCH6g==,type:str]
    version: 3.13.3
