---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "payments-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "payments"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.payments.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.payments.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.payments.port_http | int | toString }}"
  PAYMENTS_DB_HOST: "{{ .Values.config.payments.PAYMENTS_DB_HOST }}"
  PAYMENTS_DB_PORT: "{{ .Values.config.payments.PAYMENTS_DB_PORT }}"
  PAYMENTS_DB_USERNAME: "{{ .Values.config.payments.PAYMENTS_DB_USERNAME }}"
  PAYMENTS_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.payments.PAYMENTS_DB_JDBCCONNECTIONSTRING }}"
  PAYMENTS_DB_DATABASENAME: "{{ .Values.config.payments.PAYMENTS_DB_DATABASENAME }}"
  CACHE_HOST: "{{ .Values.config.payments.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.payments.CACHE_PORT }}"
  MESSAGING_HOST: "{{ .Values.config.payments.MESSAGING_HOST }}"
  MESSAGING_PORT: "{{ .Values.config.payments.MESSAGING_PORT }}"
  MESSAGING_USERNAME: "{{ .Values.config.payments.MESSAGING_USERNAME }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.payments.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.payments.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.payments.OTEL_SERVICE_NAME }}"
