---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "payments-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "payments"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__payments-db: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.payments.postgres_password }};Database=payments"
  PAYMENTS_DB_PASSWORD: "{{ .Values.secrets.payments.postgres_password }}"
  PAYMENTS_DB_URI: "postgresql://postgres:{{ .Values.secrets.payments.postgres_password }}@postgres-service:5432/payments"
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.payments.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.payments.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.payments.cache_password }}@cache-service:6379"
  ConnectionStrings__messaging: "amqp://guest:{{ .Values.secrets.payments.messaging_password }}@messaging-service:5672"
  MESSAGING_PASSWORD: "{{ .Values.secrets.payments.messaging_password }}"
  MESSAGING_URI: "amqp://guest:{{ .Values.secrets.payments.messaging_password }}@messaging-service:5672"
type: "Opaque"
