---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "messaging-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "messaging"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.config.messaging.RABBITMQ_DEFAULT_USER }}"
