---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "messaging-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "messaging"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  RABBITMQ_DEFAULT_PASS: "{{ .Values.secrets.messaging.messaging_password }}"
type: "Opaque"
