---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bookings-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bookings"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bookings.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bookings.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.bookings.port_http | int | toString }}"
  BOOKINGS_DB_HOST: "{{ .Values.config.bookings.BOOKINGS_DB_HOST }}"
  BOOKINGS_DB_PORT: "{{ .Values.config.bookings.BOOKINGS_DB_PORT }}"
  BOOKINGS_DB_USERNAME: "{{ .Values.config.bookings.BOOKINGS_DB_USERNAME }}"
  BOOKINGS_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.bookings.BOOKINGS_DB_JDBCCONNECTIONSTRING }}"
  BOOKINGS_DB_DATABASENAME: "{{ .Values.config.bookings.BOOKINGS_DB_DATABASENAME }}"
  CACHE_HOST: "{{ .Values.config.bookings.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.bookings.CACHE_PORT }}"
  MESSAGING_HOST: "{{ .Values.config.bookings.MESSAGING_HOST }}"
  MESSAGING_PORT: "{{ .Values.config.bookings.MESSAGING_PORT }}"
  MESSAGING_USERNAME: "{{ .Values.config.bookings.MESSAGING_USERNAME }}"
  SCREENINGS_HTTP: "http://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  services__screenings__http__0: "http://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  SCREENINGS_HTTPS: "https://screenings-service:{{ .Values.parameters.screenings.port_http }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.bookings.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.bookings.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.bookings.OTEL_SERVICE_NAME }}"
