---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bookings-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bookings"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__bookings-db: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.bookings.postgres_password }};Database=bookings"
  BOOKINGS_DB_PASSWORD: "{{ .Values.secrets.bookings.postgres_password }}"
  BOOKINGS_DB_URI: "postgresql://postgres:{{ .Values.secrets.bookings.postgres_password }}@postgres-service:5432/bookings"
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.bookings.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.bookings.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.bookings.cache_password }}@cache-service:6379"
  ConnectionStrings__messaging: "amqp://guest:{{ .Values.secrets.bookings.messaging_password }}@messaging-service:5672"
  MESSAGING_PASSWORD: "{{ .Values.secrets.bookings.messaging_password }}"
  MESSAGING_URI: "amqp://guest:{{ .Values.secrets.bookings.messaging_password }}@messaging-service:5672"
type: "Opaque"
